### ISSUE TITLE
Upgrade cookbook  chef-vault dependency

### ISSUE THREAD

**Issue by marcusn** [onbeep-cookbooks/ssl-vault#5]

**Comment by joerg** [comment]
+1 I am just having the same problem. ;)

**Comment by jkupferer** [comment]
+1 Same thing here. I just hacked the metadata.rb to allow 1.3.0 and it worked great.

**Comment by gshively11** [comment]
:+1:

**Comment by mjuarez** [comment]
Tracking this work in https://github.com/onbeep-cookbooks/ssl-vault/pull/7

**Comment by mjuarez** [comment]
Merged in, this should be fix issues. Let me know!

**Comment by gshively11** [comment]
It works, thanks @mjuarez!
